name: Update Brew Tap

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  update-tap:
    runs-on: ubuntu-latest
    steps:
      - name: Get release info
        id: release
        run: |
          VERSION=${{ github.event.release.tag_name }}
          URL="https://github.com/${{ github.repository }}/archive/refs/tags/$VERSION.tar.gz"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "url=$URL" >> $GITHUB_OUTPUT
          
          # Download the tarball and calculate its SHA256
          curl -sL "$URL" | sha256sum | cut -d' ' -f1 > sha.txt
          SHA=$(cat sha.txt)
          echo "sha256=$SHA" >> $GITHUB_OUTPUT

      - name: Checkout tap repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/homebrew-tap
          token: ${{ secrets.TAP_REPO_TOKEN }}
          path: tap

      - name: Update Formula
        run: |
          cd tap
          cat > Formula/lazygit.rb << EOL
          class Lazygit < Formula
            desc "A simple terminal UI for git commands"
            homepage "https://github.com/${{ github.repository }}"
            url "${{ steps.release.outputs.url }}"
            sha256 "${{ steps.release.outputs.sha256 }}"
            version "${{ steps.release.outputs.version }}"
            license "MIT"

            depends_on "go" => :build

            def install
              system "go", "build", *std_go_args(ldflags: "-X main.version=\#{version}")
            end

            test do
              system bin/"lazygit", "--version"
            end
          end
          EOL

      - name: Commit and push changes
        run: |
          cd tap
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add Formula/lazygit.rb
          git commit -m "lazygit ${{ steps.release.outputs.version }}"
          git push 